version: '3.1'
services:
  server:
    ports:
      - 1234:1234
    depends_on:
      - mongodb
    environment:
      PORT: 1234
      JWT_SECRET: RMxcllZRO5FCurG6zZGeB2vyg7WBxuLCSYl1Qx127H9zZ55qe6XsGABY47MVuwm
      MONGO_URI: mongodb://root:example@mongodb:27017
      MONGO_DB: cluster0
    build:
      context: .
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongodb-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
