openapi: 3.1.0
info:
  title: ""
  version: "" 
paths:
  /auth:
    post:
      summary: Logs in and returns the authentication  cookie
      security: []
      parameters:
        - name: guid
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/JWT'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '400':
          $ref: '#/components/responses/InternalServerError'
  /refresh:
    post:
      summary: Refreshes JWT token
      security: []
      responses:
        '200':
          $ref: '#/components/responses/JWT'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '400':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 

  responses:
    JWT:
      description: >
        JWT access token with expiration date.
        JWT refresh token is returned in a cookie named `refresh_token`.
      content:
        application/json:
          schema:
            type: object
            required:
              - access_token
              - expires_at
            properties:
              access_token:
                type: string
              expires_at:
                type: integer
                format: int64
      headers:
        Set-Cookie:
          schema: 
            type: string
            example: refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c; HttpOnly

    UnauthorizedError:
      description: Access token is missing or invalid
    InternalServerError:
      description: Internal server error
